services:

  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/mnt
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      timeout: 5s
      retries: 5
    # command: ["pg_restore", "-U", "postgres", "-d", "dvdrental", "/mnt/dvdrental"]

networks:
  backend:
    driver: bridge