-- Sample data for Customer and Address tables
-- This will run automatically when PostgreSQL container starts

-- Create tables to match your JPA entities
CREATE TABLE IF NOT EXISTS address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255),
    address2 VARCHAR(255),
    district VARCHAR(255),
    city_id INTEGER,
    postal_code VARCHAR(255),
    phone VARCHAR(255),
    last_update TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INTEGER,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    address_id BIGINT UNIQUE,
    activebool BOOLEAN,
    active INTEGER,
    create_date TIMESTAMP(6),
    last_update TIMESTAMP(6),
    CONSTRAINT fk_customer_address FOREIGN KEY (address_id) REFERENCES address (address_id)
);

-- Insert sample addresses
INSERT INTO address (address, address2, district, city_id, postal_code, phone, last_update) VALUES
('123 Main St', 'Apt 1', 'Downtown', 1, '12345', '555-0101', NOW()),
('456 Oak Ave', NULL, 'Suburbs', 2, '67890', '555-0102', NOW()),
('789 Pine Rd', 'Suite 200', 'Business District', 3, '54321', '555-0103', NOW());

-- Insert sample customers
INSERT INTO customer (store_id, first_name, last_name, email, address_id, activebool, active, create_date, last_update) VALUES
(1, 'John', 'Doe', 'john.doe@email.com', 1, true, 1, NOW(), NOW()),
(1, 'Jane', 'Smith', 'jane.smith@email.com', 2, true, 1, NOW(), NOW()),
(2, 'Bob', 'Johnson', 'bob.johnson@email.com', 3, true, 1, NOW(), NOW());